#!/usr/bin/env python3
"""
Abra Life OS — Interactive Setup
Run once: python3 setup.py
Sets up everything a new user needs in under 5 minutes.
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.resolve()
ENV_PATH = PROJECT_ROOT / ".env"
SOURCES_DIR = PROJECT_ROOT / "sources"
BRAIN_DIR = PROJECT_ROOT / "brain_files"

# ──────────────────────────────────────────────
# Colors for terminal output
# ──────────────────────────────────────────────
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"


def banner():
    print(f"""
{CYAN}{BOLD}
    ╔═══════════════════════════════════════════╗
    ║          ABRA — Personal Life OS          ║
    ║            Interactive Setup              ║
    ╚═══════════════════════════════════════════╝{RESET}
{DIM}  Voice-first AI life dashboard powered by Coral SQL{RESET}
""")


def ask(prompt, default=None, secret=False, required=True):
    """Prompt user for input with optional default."""
    suffix = f" [{default}]" if default else ""
    if secret:
        suffix += " (hidden)"
    
    while True:
        value = input(f"  {CYAN}→{RESET} {prompt}{suffix}: ").strip()
        if not value and default:
            return default
        if value:
            return value
        if not required:
            return ""
        print(f"  {RED}  This field is required.{RESET}")


def ask_yes_no(prompt, default=True):
    """Ask a yes/no question."""
    suffix = "[Y/n]" if default else "[y/N]"
    answer = input(f"  {CYAN}→{RESET} {prompt} {suffix}: ").strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def section(title):
    print(f"\n{BOLD}{GREEN}━━━ {title} ━━━{RESET}\n")


def success(msg):
    print(f"  {GREEN}✓{RESET} {msg}")


def warn(msg):
    print(f"  {YELLOW}⚠{RESET} {msg}")


def error(msg):
    print(f"  {RED}✗{RESET} {msg}")


def write_env(config: dict):
    """Writes configuration to .env file."""
    lines = ["# Abra Life OS — Auto-generated by setup.py\n"]
    
    sections = {
        "Notion Integration": ["NOTION_TOKEN", "NOTION_DIARY_DB_ID", "NOTION_TASKS_DB_ID", "NOTION_BRAIN_PAGE_ID"],
        "Chess.com": ["CHESSCOM_USERNAME"],
        "LLM Provider": ["LLM_PROVIDER", "GEMINI_API_KEY", "GROQ_API_KEY", "CEREBRAS_API_KEY"],
        "Strava": ["STRAVA_ACCESS_TOKEN", "STRAVA_CLIENT_ID", "STRAVA_CLIENT_SECRET", "STRAVA_REFRESH_TOKEN", "STRAVA_TOKEN_EXPIRES_AT"],
    }
    
    for section_name, keys in sections.items():
        section_keys = {k: v for k, v in config.items() if k in keys and v}
        if section_keys:
            lines.append(f"\n# {section_name}")
            for k, v in section_keys.items():
                lines.append(f'{k}="{v}"')
    
    # Write any remaining keys not in sections
    written = set()
    for keys in sections.values():
        written.update(keys)
    remaining = {k: v for k, v in config.items() if k not in written and v}
    if remaining:
        lines.append("\n# Other")
        for k, v in remaining.items():
            lines.append(f'{k}="{v}"')
    
    ENV_PATH.write_text("\n".join(lines) + "\n")
    success(f"Configuration written to {ENV_PATH.name}")


def setup_brain_files():
    """Creates the brain_files directory with template files for new users."""
    BRAIN_DIR.mkdir(exist_ok=True)
    
    templates = {
        "master_profile.md": """# Master Profile
<!-- Write about yourself: who you are, what you do, your background -->
<!-- Abra uses this to personalize every response -->

## About Me
- Name: 
- Location: 
- Occupation: 

## Background
<!-- Your story, education, interests -->

## What Matters To Me
<!-- Core values, priorities -->
""",
        "career_plan.md": """# Current Goals & Milestones
<!-- Track your active goals here. Abra will reference these in briefings. -->

## Active Goals
- [ ] Goal 1: 
- [ ] Goal 2: 
- [ ] Goal 3: 

## This Week's Focus
<!-- What are you prioritizing this week? -->
""",
        "patterns_for_ai_interaction.md": """# Mental & Behavioral Patterns
<!-- Document patterns you want Abra to watch for and call out -->
<!-- Example: "I tend to procrastinate by switching tools instead of doing the work" -->

## Patterns to Watch
- 

## Triggers
- 

## What Helps
- 
"""
    }
    
    for filename, content in templates.items():
        filepath = BRAIN_DIR / filename
        if not filepath.exists():
            filepath.write_text(content)
            success(f"Created template: brain_files/{filename}")
        else:
            success(f"Already exists: brain_files/{filename}")


def check_coral():
    """Check if Coral CLI is installed."""
    try:
        result = subprocess.run(["coral", "--version"], capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            version = result.stdout.strip()
            success(f"Coral CLI detected: {version}")
            return True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return False


def register_coral_sources():
    """Register all source specs with Coral."""
    specs = list(SOURCES_DIR.glob("*.yml")) + list(SOURCES_DIR.glob("*.yaml"))
    if not specs:
        warn("No source spec files found in sources/")
        return
    
    for spec in specs:
        name = spec.stem
        print(f"  Registering {name}...", end=" ", flush=True)
        try:
            result = subprocess.run(
                ["coral", "source", "add", "--file", str(spec)],
                capture_output=True, text=True, timeout=15
            )
            if result.returncode == 0:
                print(f"{GREEN}✓{RESET}")
            else:
                print(f"{YELLOW}⚠ {result.stderr.strip()[:80]}{RESET}")
        except Exception as e:
            print(f"{RED}✗ {e}{RESET}")


def install_dependencies():
    """Install Python dependencies."""
    print("  Installing Python dependencies...")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", str(PROJECT_ROOT / "requirements.txt"), "-q"],
            capture_output=True, text=True, timeout=120
        )
        if result.returncode == 0:
            success("All Python dependencies installed")
        else:
            warn(f"pip install had issues: {result.stderr.strip()[:100]}")
    except Exception as e:
        error(f"Failed to install dependencies: {e}")


# ──────────────────────────────────────────────
# Main Setup Flow
# ──────────────────────────────────────────────

def main():
    banner()
    config = {}
    
    # Check for existing .env
    if ENV_PATH.exists():
        if not ask_yes_no("Existing .env found. Overwrite with fresh setup?", default=False):
            print(f"\n  {DIM}Keeping existing .env. Run with --force to overwrite.{RESET}")
            # Still offer to register sources
            if check_coral() and ask_yes_no("Register/update Coral sources?"):
                register_coral_sources()
            print(f"\n{GREEN}{BOLD}  Setup complete! Run: python3 main.py{RESET}\n")
            return
    
    # ── Step 1: LLM Provider ──
    section("1/5 · LLM Provider")
    print(f"  Abra needs an LLM to think. Pick your provider:")
    print(f"  {DIM}  1. Gemini (Google — recommended, free tier available)")
    print(f"    2. Groq (fast inference, free tier)")
    print(f"    3. Cerebras (fast inference){RESET}")
    
    provider_choice = ask("Choose provider (1/2/3)", default="1")
    provider_map = {"1": "gemini", "2": "groq", "3": "cerebras"}
    config["LLM_PROVIDER"] = provider_map.get(provider_choice, "gemini")
    
    if config["LLM_PROVIDER"] == "gemini":
        config["GEMINI_API_KEY"] = ask("Gemini API key (https://aistudio.google.com/apikey)")
    elif config["LLM_PROVIDER"] == "groq":
        config["GROQ_API_KEY"] = ask("Groq API key (https://console.groq.com/keys)")
    elif config["LLM_PROVIDER"] == "cerebras":
        config["CEREBRAS_API_KEY"] = ask("Cerebras API key")
    
    # Optional: add secondary provider for fallback
    if config["LLM_PROVIDER"] == "gemini":
        if ask_yes_no("Add Groq as fallback + Whisper voice transcription?", default=False):
            config["GROQ_API_KEY"] = ask("Groq API key (https://console.groq.com/keys)")
    
    success(f"LLM provider: {config['LLM_PROVIDER']}")
    
    # ── Step 2: Notion ──
    section("2/5 · Notion Integration")
    print(f"  Abra writes diary entries and reads tasks from Notion.")
    print(f"  {DIM}  Create an integration at: https://www.notion.so/my-integrations{RESET}")
    
    if ask_yes_no("Set up Notion integration?"):
        config["NOTION_TOKEN"] = ask("Notion integration token (starts with ntn_)")
        config["NOTION_API_KEY"] = config["NOTION_TOKEN"]  # Alias
        config["NOTION_DIARY_DB_ID"] = ask("Diary database ID (32-char hex from URL)", required=False)
        config["NOTION_TASKS_DB_ID"] = ask("Tasks database ID (32-char hex from URL)", required=False)
        config["NOTION_BRAIN_PAGE_ID"] = ask("Brain parent page ID (optional)", required=False)
        success("Notion configured")
    else:
        warn("Skipping Notion. Diary entries will save to local files.")
    
    # ── Step 3: Chess.com ──
    section("3/5 · Chess.com")
    print(f"  Track your chess ratings and game history. No API key needed.")
    
    if ask_yes_no("Connect Chess.com?"):
        config["CHESSCOM_USERNAME"] = ask("Your Chess.com username")
        success(f"Chess.com: {config['CHESSCOM_USERNAME']}")
    else:
        warn("Skipping Chess.com")
    
    # ── Step 4: Strava ──
    section("4/5 · Strava")
    print(f"  Track running, cycling, and fitness data.")
    print(f"  {DIM}  Create an app at: https://www.strava.com/settings/api")
    print(f"    Set callback domain to: localhost{RESET}")
    
    if ask_yes_no("Connect Strava?"):
        config["STRAVA_CLIENT_ID"] = ask("Strava Client ID")
        config["STRAVA_CLIENT_SECRET"] = ask("Strava Client Secret")
        
        if ask_yes_no("Do you already have an access token?", default=False):
            config["STRAVA_ACCESS_TOKEN"] = ask("Strava Access Token")
            config["STRAVA_REFRESH_TOKEN"] = ask("Strava Refresh Token", required=False)
        else:
            print(f"\n  {DIM}  Run this after setup to authenticate:")
            print(f"    python3 coral_startup.py --strava-auth{RESET}\n")
        
        success("Strava configured")
    else:
        warn("Skipping Strava")
    
    # ── Step 5: Write config & finalize ──
    section("5/5 · Finalizing")
    
    # Write .env
    write_env(config)
    
    # Create brain files directory
    print()
    setup_brain_files()
    
    # Install Python deps
    print()
    if ask_yes_no("Install Python dependencies?"):
        install_dependencies()
    
    # Check and register Coral sources
    print()
    has_coral = check_coral()
    if has_coral:
        if ask_yes_no("Register source specs with Coral?"):
            register_coral_sources()
    else:
        warn("Coral CLI not found. Install it: https://withcoral.com/docs/getting-started/installation")
        print(f"  {DIM}  After installing, run: python3 coral_startup.py{RESET}")
    
    # ── Done ──
    print(f"""
{GREEN}{BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{RESET}
{GREEN}{BOLD}  ✓ Abra is ready!{RESET}

  {BOLD}Start the server:{RESET}
    python3 main.py

  {BOLD}Open the dashboard:{RESET}
    http://127.0.0.1:8000

  {BOLD}Optional next steps:{RESET}
    • Edit brain_files/ to personalize Abra's context
    • Run {CYAN}python3 coral_startup.py --strava-auth{RESET} for Strava OAuth
    • Run {CYAN}coral source lint sources/chesscom.yml{RESET} to validate specs
{GREEN}{BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{RESET}
""")


if __name__ == "__main__":
    main()
